//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notadesigner.Cadence.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GuiRunnerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiRunnerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notadesigner.Cadence.Windows.Properties.GuiRunnerResources", typeof(GuiRunnerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to begin again.
        /// </summary>
        internal static string AbandonedToolTip {
            get {
                return ResourceManager.GetString("AbandonedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string BeginToolTip {
            get {
                return ResourceManager.GetString("BeginToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. Reset to begin again..
        /// </summary>
        internal static string EndToolTip {
            get {
                return ResourceManager.GetString("EndToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than a minute elapsed.
        /// </summary>
        internal static string LessThanOneMinuteElapsedToolTip {
            get {
                return ResourceManager.GetString("LessThanOneMinuteElapsedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0} minutes elapsed.
        /// </summary>
        internal static string MoreThanOneMinuteElapsedToolTipTemplate {
            get {
                return ResourceManager.GetString("MoreThanOneMinuteElapsedToolTipTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One minute elapsed.
        /// </summary>
        internal static string OneMinuteElapsedToolTip {
            get {
                return ResourceManager.GetString("OneMinuteElapsedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadence.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break completed..
        /// </summary>
        internal static string RefreshedEnterNotification {
            get {
                return ResourceManager.GetString("RefreshedEnterNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for a short break..
        /// </summary>
        internal static string RelaxedEnterNotification {
            get {
                return ResourceManager.GetString("RelaxedEnterNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! Take a long break..
        /// </summary>
        internal static string StoppedEnterNotification {
            get {
                return ResourceManager.GetString("StoppedEnterNotification", resourceCulture);
            }
        }
    }
}
